version: '3.2'
services:
  bash:
    image: learncli/bash
    working_dir: /mnt/learncli/workdir
    volumes:
      - type: bind
        source: "${WORKDIR:-./}"
        target: /mnt/learncli
  comp211:
    # From github.com:comp211/comp211-container
    image: learncli/comp211:latest
    working_dir: /mnt/learncli/workdir
    volumes:
      - type: bind
        source: "${WORKDIR:-./}"
        target: /mnt/learncli
  comp530:
    # From github.com:comp530-f22/comp530-container
    image: learncli/comp530:latest
    working_dir: /mnt/learncli/workdir
    volumes:
      - type: bind
        source: "${WORKDIR:-./}"
        target: /mnt/learncli
